Controllers/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AccessoPaso1.Models;

namespace AccessoPaso1.Controllers
{
    

    public class CatalogoController : Controller
    {
        private contextTienda db = new contextTienda();
        // GET: Catalogo
        public ActionResult Index()
        {
            using (db)
            {
                var query = from st in db.Productoes
                    select st;
                var listProd = query.ToList();
                ViewBag.Listado = listProd;
            }
            return View();
        }
        [HttpPost]
        public ActionResult BuscaProd(string nomBuscar)
        {
            ViewBag.SearchKey = nomBuscar;
            using (db)
            {
                var query = from st in db.Productoes
                            where st.nombre.Contains(nomBuscar)

                            select st;
                var listProd = query.ToList();
                ViewBag.Listado = listProd;
            }
            return View();
        }


       
        public ActionResult prodCategoria(int idCat,string nombre)
        {   
            List<Producto> mercancia = null;
            var query = from p in db.Productoes
                        where p.id_categoria == idCat
                        select p;

            mercancia = query.ToList();
            ViewBag.Catego = nombre;
            ViewBag.productos = mercancia;
            return View();
        }
    }
}

Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AccessoPaso1.Models;

namespace AccessoPaso1.Controllers
{
    public class ProductoController : Controller
    {
        private contextTienda db = new contextTienda();

        // GET: Producto
        public ActionResult Index()
        {
            var producto = db.Productoes.Include(p => p.Categoria);
            return View(producto.ToList());
        }

        // GET: Producto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            ViewBag.id_categoria = new SelectList(db.Categorias, "Id_categoria", "nombre");
            return View();
        }

        // POST: Producto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_producto,nombre,descripcion,precio,imgen,existencia,stock,id_categoria")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Productoes.Add(producto);
                db.SaveChanges();
                int id = producto.Id_producto;
                var prod = db.Productoes.Find(id);
                DateTime hoy = DateTime.Now;
                prod.ult_actualizacion = hoy;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_categoria = new SelectList(db.Categorias, "Id_categoria", "nombre", producto.id_categoria);
            return View(producto);
        }

        // GET: Producto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_categoria = new SelectList(db.Categorias, "Id_categoria", "nombre", producto.id_categoria);
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_producto,nombre,descripcion,precio,ult_actualizacion,imgen,existencia,stock,id_categoria")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                int id = producto.Id_producto;
                var prod = db.Productoes.Find(id);
                decimal precio_ant = prod.precio;
                decimal precio_act = producto.precio;
                // db.Entry(producto).State = EntityState.Modified;
                prod.nombre = producto.nombre;
                prod.descripcion = producto.descripcion;
                prod.precio = producto.precio;
                prod.imgen = producto.imgen;
                prod.existencia = producto.existencia;
                prod.stock = producto.stock;
                prod.id_categoria = producto.id_categoria;
                if (precio_act != precio_ant)
                {
                    DateTime hoy = DateTime.Now;
                    prod.ult_actualizacion = hoy;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_categoria = new SelectList(db.Categorias, "Id_categoria", "nombre", producto.id_categoria);
            return View(producto);
        }

        // GET: Producto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Productoes.Find(id);
            db.Productoes.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Catalogo/BuscaCat.cshtml
@using AccessoPaso1.Models
@{
    ViewBag.Title = "BuscaCat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">

    <h3> Categoria @ViewBag.SearchKey</h3>
    <div class="container">
        <div class="row">
            @foreach (Producto producto in ViewBag.Listado)
            {
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="~/Content/img/@producto.imgen" width="60" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@producto.nombre</h5>
                            <p class="card-text">@producto.descripcion</p>
                            <a href="@Url.Action("Comprar","Carro", new {id = producto.Id_producto})" class="btn btn-primary">$@producto.precio</a>
                        </div>
                    </div>
                </div>



            }

        </div>
    </div>
</div>

Views/Catalogo/BuscaProd.cshtml
@using AccessoPaso1.Models
@{
    ViewBag.Title = "BuscaProd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">

    <h3> Lista de productos con nombre @ViewBag.SearchKey</h3>
    <div class="container">
        <div class="row">
            @foreach (Producto producto in ViewBag.Listado)
            {
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="~/Content/img/productos/@producto.imgen" width="60" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@producto.nombre</h5>
                            <p class="card-text">@producto.descripcion</p>
                            <h4>$@producto.precio</h4>
                            <a href="@Url.Action("Comprar","Carro", new {id = producto.Id_producto})" class="btn btn-primary">Agregar al carrito</a>
                        </div>
                    </div>
                </div>



            }

        </div>
    </div>
    </div>

Views/Catalogo/Index.cshtml

@using AccessoPaso1.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="container">
    <h3> Catalogo</h3>

    <div class="row">
        @foreach (Producto producto in ViewBag.Listado)
        {
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="~/Content/img/productos/@producto.imgen" width="60" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@producto.nombre</h5>
                        <p class="card-text">@producto.descripcion</p>
                        <h4>$@producto.precio</h4>
                        <a href="@Url.Action("Comprar", "Carro", new {id = producto.Id_producto})" class="btn btn-primary">Agregar al carrito</a>
                    </div>
                </div>
            </div>



        }

    </div>
</div>
</div>


Views/Catalogo/prodCategoria.cshtml
@using AccessoPaso1.Models
@{
    ViewBag.Title = "prodCategoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">

    <h3> @ViewBag.Catego</h3>
    <div class="container">
        <div class="row">
            @foreach (Producto producto in ViewBag.productos)
            {
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="~/Content/img/productos/@producto.imgen" width="60" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">@producto.nombre</h5>
                            <p class="card-text">@producto.descripcion</p>
                            <h4>$@producto.precio</h4>
                            <a href="@Url.Action("Comprar","Carro", new {id = producto.Id_producto})" class="btn btn-primary">Agregar al carrito</a>
                        </div>
                    </div>
                </div>

            }

        </div>
    </div>
</div>

Views/Producto/Create.cshtml
@model AccessoPaso1.Models.Producto

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.imgen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imgen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imgen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.existencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.existencia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.existencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_categoria, "id_categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Producto/Delete.cshtml
@model AccessoPaso1.Models.Producto

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<div class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Producto</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.precio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.precio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ult_actualizacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ult_actualizacion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.imgen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.imgen)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.existencia)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.existencia)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.stock)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stock)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Categoria.nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Categoria.nombre)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

</div>

Views/Producto/Details.cshtml
@model AccessoPaso1.Models.Producto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<div class="container">
    <h2>Details</h2>

    <div>
        <h4>Producto</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.descripcion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.descripcion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.precio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.precio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ult_actualizacion)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ult_actualizacion)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.imgen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.imgen)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.existencia)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.existencia)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.stock)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.stock)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Categoria.nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Categoria.nombre)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id_producto }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

</div>

Views/Producto/Edit.cshtml
@model AccessoPaso1.Models.Producto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<div class="container">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Producto</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id_producto)

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                </div>
            </div>

            
            <div class="form-group">
                @Html.LabelFor(model => model.imgen, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.imgen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.imgen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.existencia, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.existencia, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.existencia, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.id_categoria, "id_categoria", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

Views/Producto/Index.cshtml
@model IEnumerable<AccessoPaso1.Models.Producto>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCompras.cshtml";
}

<div >
    <h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precio)
            </th>
            <th>
                Ultima actualizacion
            </th>
            <th>
                @Html.DisplayNameFor(model => model.imgen)
                
            </th>
            <th>
                @Html.DisplayNameFor(model => model.existencia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.stock)
            </th>
            <th>
               Categoria
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ult_actualizacion)
                </td>
                <td>
                    <img src="~/Content/img/productos/@Html.DisplayFor(modelItem => item.imgen)" class="card-img-top" alt="...">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.existencia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.stock)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Categoria.nombre)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id_producto }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id_producto }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id_producto })
                </td>
            </tr>
        }

    </table>
</div>

Views/Shared/_LayoutEnvios.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/style.css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Content/style.css">
</head>
<body>
    <!--Header-->
    <div>
        <img src="~/Content/img/Envio.png" alt="Responsive image" class="img-fluid banner">
        <!--barra de navegacion-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <img src="~/Content/img/logo.svg" width="30" height="30" class="logo espacio-nav d-inline-block align-top" alt="">
            <a class="navbar-brand" href="#">@Html.ActionLink("Mymodels", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                    <li class=" ml-3">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class=" ml-3">@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li class=" ml-3">@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li class=" ml-3">
                        @using (Html.BeginForm("BuscaProd", "Catalogo", FormMethod.Post, new {@class = "Form-inline" }))
                        {
                            <input class="form-control mr-sm-2" type="text" id="nomBuscar" name="nomBuscar" placeholder="producto" >
                            

                        }
                    </li>
                </ul>
                @Html.Partial("_LoginPartial1")

            </div>

        </nav>
    </div>


    <div class="">
        @RenderBody()
        <hr />

    </div>
    <div>
        <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                    </div>

                    <div class="col-xs-6 col-md-3">
                        <h6>Acerca de</h6>
                        <ul class="footer-links">
                            <li><a href="#">Politicas de devoluciones</a></li>
                            <li><a href="#">Envios</a></li>
                            <li><a href="#">Avisos de privacidad</a></li>
                            <li><a href="#">Terminos y condiciones</a></li>
                        </ul>
                    </div>

                    <div class="col-xs-6 col-md-3">
                        <h6>Contacto</h6>
                        <ul class="footer-links">
                            <li><a>+52 722 111 1111 </a></li>
                            <li><a href="mailto:soporte@mymodels.com">soporte@mymodels.com</a></li>
                        </ul>
                    </div>
                </div>
                <hr>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-6 col-xs-12">
                        <p class="copyright-text">
                            Copyright &copy; 2020 Todos los derechos reservados para
                            <a href="#">mymodels</a>.
                        </p>
                    </div>

                    <!--
                                <div class="col-md-4 col-sm-6 col-xs-12">
                        <ul class="social-icons">
                          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                          <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
                          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                      </div>
                    -->
                </div>
            </div>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>